#!/usr/bin/env bash
# RemminaMac installer -- macOS and Linux
# Usage: bash install.sh
set -euo pipefail

REPO_URL="https://github.com/georgegozal/remminamac.git"
INSTALL_DIR="$HOME/.local/share/remminamac"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/remminamac"
DESKTOP_FILE="$HOME/.local/share/applications/remminamac.desktop"
ICON_SRC="$INSTALL_DIR/assets/screenshot.png"

# -- Colour helpers -----------------------------------------------------------
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[remminamac]${NC} $*"; }
warn()  { echo -e "${YELLOW}[remminamac]${NC} $*"; }
error() { echo -e "${RED}[remminamac] ERROR:${NC} $*" >&2; exit 1; }

# -- Platform detection -------------------------------------------------------
PLATFORM=""
_uname="$(uname -s)"
if [[ "$_uname" == "Darwin" ]]; then
    PLATFORM="macos"
elif [[ "$_uname" == "Linux" ]]; then
    PLATFORM="linux"
else
    error "Unsupported OS: ${_uname}"
fi

info "Installing RemminaMac on ${PLATFORM}..."

# -- Python check -------------------------------------------------------------
PYTHON=""
for py in python3.13 python3.12 python3.11 python3.10 python3; do
  if command -v "$py" &>/dev/null; then
    if "$py" -c 'import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)' 2>/dev/null; then
      PYTHON="$py"
      break
    fi
  fi
done
[[ -z "$PYTHON" ]] && error "Python 3.10+ is required. Install it and re-run."
info "Using $("${PYTHON}" --version)"

# -- Git check ----------------------------------------------------------------
command -v git &>/dev/null || error "git is required. Install it and re-run."

# -- Clone or update ----------------------------------------------------------
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Updating existing installation..."
  git -C "$INSTALL_DIR" pull --ff-only
else
  info "Cloning RemminaMac to ${INSTALL_DIR}..."
  git clone --depth=1 "$REPO_URL" "$INSTALL_DIR"
fi

# -- Python virtual environment -----------------------------------------------
VENV="$INSTALL_DIR/.venv"
if [[ ! -d "$VENV" ]]; then
  info "Creating virtual environment..."
  "$PYTHON" -m venv "$VENV"
fi

info "Installing Python dependencies..."
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$INSTALL_DIR/requirements.txt"

# -- Linux: optional SecretService backend for keyring ------------------------
if [[ "$PLATFORM" == "linux" ]]; then
  if "$VENV/bin/python" -c "import secretstorage" 2>/dev/null; then
    : # already installed
  else
    warn "secretstorage not found. Passwords will be stored in a local file instead of"
    warn "GNOME Keyring / KWallet. Install it for better security:"
    warn "  pip install secretstorage   (or: apt install python3-secretstorage)"
    "$VENV/bin/pip" install --quiet secretstorage 2>/dev/null || true
  fi
fi

# -- Shell launcher -----------------------------------------------------------
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# RemminaMac launcher -- auto-generated by install.sh
exec "$VENV/bin/python" "$INSTALL_DIR/main.py" "\$@"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
info "Launcher created: ${LAUNCHER}"

# -- Linux: .desktop file -----------------------------------------------------
if [[ "$PLATFORM" == "linux" ]]; then
  mkdir -p "$(dirname "$DESKTOP_FILE")"

  if [[ -f "$ICON_SRC" ]]; then
    ICON_VALUE="$ICON_SRC"
  else
    ICON_VALUE="utilities-terminal"
  fi

  cat > "$DESKTOP_FILE" << DESKTOP_EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=RemminaMac
Comment=SSH connection manager for macOS and Linux
Exec=$LAUNCHER %u
Icon=$ICON_VALUE
Terminal=false
Categories=Network;RemoteAccess;
Keywords=ssh;terminal;remote;connection;
DESKTOP_EOF

  command -v update-desktop-database &>/dev/null && \
    update-desktop-database "$HOME/.local/share/applications" 2>/dev/null || true

  info ".desktop file created: ${DESKTOP_FILE}"
fi

# -- macOS: PATH setup --------------------------------------------------------
if [[ "$PLATFORM" == "macos" ]]; then
  _detect_shell_rc() {
    local shell_name
    shell_name="$(basename "${SHELL:-bash}")"
    case "$shell_name" in
      zsh)  echo "$HOME/.zshrc" ;;
      bash) echo "$HOME/.bashrc" ;;
      fish) echo "$HOME/.config/fish/config.fish" ;;
      *)    echo "$HOME/.profile" ;;
    esac
  }
  SHELL_RC="$(_detect_shell_rc)"

  if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
    PATH_LINE="export PATH=\"\$HOME/.local/bin:\$PATH\""
    echo ""
    warn "$BIN_DIR is not in your PATH."
    read -r -p "    Add it to $SHELL_RC automatically? [Y/n] " yn
    if [[ "$yn" != [Nn]* ]]; then
      echo "" >> "$SHELL_RC"
      echo "# Added by RemminaMac installer" >> "$SHELL_RC"
      echo "$PATH_LINE" >> "$SHELL_RC"
      info "Added PATH entry to ${SHELL_RC}"
      export PATH="$BIN_DIR:$PATH"
    else
      warn "Skipped. Add this line manually to your shell config:"
      warn "  $PATH_LINE"
    fi
  fi
fi

# -- Done ---------------------------------------------------------------------
echo ""
info "RemminaMac installed successfully!"
info "Run it with:  remminamac"
if [[ "$PLATFORM" == "macos" ]]; then
  info "(Restart your terminal if 'remminamac' is not found yet)"
fi
